<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE errores [
<!ELEMENT errores (fichero+)>
<!ELEMENT fichero (error+)>
<!ELEMENT error (linea , tipo)>
<!ATTLIST error tipo (t1|t2) #REQUIRED>
<!ELEMENT linea (#PCDATA)>
<!ELEMENT tipo (#PCDATA)>
<!ATTLIST fichero nombre CDATA #REQUIRED>
]>

<errores>
  <fichero nombre="ejer6.xml">
    <error tipo="t1">
      <linea>2</linea>
      <tipo>Falta el DOCTYPE al principio del fichero</tipo>
    </error>

    <error tipo="t2">
      <linea>16</linea>
      <tipo>Falta elemento Ciudad</tipo>
    </error>
  </fichero>
</errores>